yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_posts'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
]

yatube/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

yatube/about/models.py
# from django.db import models

# Create your models here.

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self) -> str:
        return self.title


class Post(models.Model):
    text = models.TextField(verbose_name='Текст поста')
    pub_date = models.DateTimeField(auto_now_add=True)
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        verbose_name='Группа'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )

    class Meta:
        ordering = ['-pub_date']

    def __str__(self) -> str:
        return self.text

yatube/posts/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        help_texts = {
            'text': 'Напишите новый текст сообщения',
            'group': 'Выберете группу',
        }
        fields = ('text', 'group')

yatube/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/about/views.py
from django.views.generic.base import TemplateView


class AboutAuthorView(TemplateView):
    template_name = 'about/author.html'


class AboutTechView(TemplateView):
    template_name = 'about/tech.html'

yatube/posts/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Group, User
from .forms import PostForm
from django.contrib.auth.decorators import login_required
from utils.pagin import get_page_context

POSTS_PER_PAGE = 10


def index(request):
    text = 'Последние обновления на сайте'
    post_list = Post.objects.all().order_by('-pub_date')
    paginator = Paginator(post_list, POSTS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'title': text,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    text = 'Группа сообщества: '
    group = get_object_or_404(Group, slug=slug)
    post_list_group = Post.objects.filter(group=group).order_by('-pub_date')
    context = {
        'group': group,
        'posts': post_list_group,
        'title': text,
    }
    context.update(get_page_context(post_list_group, request))
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    user = User.objects.get(username=username)
    posts_user = Post.objects.filter(author=user)
    posts_count = posts_user.count()
    context = {
        'author': user,
        'posts_count': posts_count,
    }
    context.update(get_page_context(user.posts.all(), request))
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post_info = get_object_or_404(Post, pk=post_id)
    authors_post = post_info.author.posts.count()
    context = {
        'post_info': post_info,
        'authors_post': authors_post,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None)
    if request.method == 'POST':
        if not form.is_valid():
            return render(request, 'posts/create_post.html', {'form': form})
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', username=request.user)
    return render(request, 'posts/create_post.html', {'form': form})


@login_required
def post_edit(request, post_id):
    template = 'posts/create_post.html'
    post = get_object_or_404(Post, id=post_id, author=request.user)
    user = request.user.get_username()
    is_edit = True
    form = PostForm(request.POST or None, instance=post)

    if request.method == 'GET':
        if user != post.author.username:
            return redirect('posts:post_detail', post.id)

    elif request.method == 'POST':
        if form.is_valid():
            form.save()
        return redirect('posts:post_detail', post.id)

    context = {
        'form': form,
        'post': post,
        'is_edit': is_edit,
    }
    return render(request, template, context)

yatube/users/views.py
from django.views.generic import CreateView
from django.urls import reverse_lazy
from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'

yatube/templates/about/author.html
{% extends "base.html" %}
{% block title %}Об авторе проекта{% endblock %}
{% block content %}
<h1>Привет, я Таня</h1>
    <p>Моя тропинка в программирование проявилась совершенно случайно. Верю, что несмотря на сложности (а без них неинтересно!) она перерастет в дело моей жизни. Ведь программирование это созидание. А у меня страсть что-нибудь сотворить))) 
      <p>Меня и мои работы можно найти <a href="https://github.com/tanyanikolaeva21">ТУТ</a></p>
    <p> В любой непонятной ситуации я всегда обращаюсь за помощью к носителю языка ^_^ </p>
    <p><img src="img/20221006.png" width="800" height="600" alt='питон'>
</p>
{% endblock %} 

yatube/templates/about/tech.html
{% extends "base.html" %}
{% block title %}Технологии{% endblock %}
{% block content %}
<div class="row">
  <h1>Вот что я умею</h1>
  {% comment %}
    Боковой блок со списком технологий 
    Займет всю ширину блока на мобильном
    и 25% при размерах экрана ≥768px
  {% endcomment %}
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Python
      </li>
      <li class="list-group-item">
        Django
      </li>
    </ul>
  </aside>
  {% comment %}
    Статья  
    Займет всю ширину блока на мобильном
    и 75% при размерах экрана ≥768px
  {% endcomment %}
  <article class="col-12 col-md-9">
    <p>В настоящий момент я уже умею: </p>
    <p>- работать с базами данных, знаю принципы их работы. Хотя путаюсь еще с миграциями, но и их тоже покорю)</p>
    <p>- создвать проект на локальном компьютере</p>
    <p>- запускать виртуальное окружение</p>
    <p>- работать в командрной строке</p>
    <p>- создавать приложения</p>
    <p>- создавать и использовать ссылки в проекте, а также их отображения</p>
  </article>
</div>
{% endblock %} 

yatube/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
  <head>    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>{% block title %}{{  title  }}{% endblock title %}</title>
  </head>
  <body>
    <header>
        {% include 'includes/header.html' %}
    </header>
    <main> 
        {% block content %}
        Главная страница проекта
      {% endblock %} 
    </main>
    <footer class="border-top text-center py-3">
    {% include 'includes/footer.html' %} 
    </footer>
  </body>
</html>

yatube/templates/includes/footer.html
<!DOCTYPE html>
<html lang="ru">
<p>© {% now "Y" %} Copyright <span style="color:red">Ya</span>tube</p>

yatube/templates/includes/header.html
{% load static %}
<!DOCTYPE html>
<h{% with request.resolver_match.view_name as view_name %}
tml lang="ru">
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:red">Ya</span>tube
      </a>
            <ul class="nav nav-pills">
        
        <li class="nav-item"> 
          <a class="nav-link {% if view_name  == 'about:author' %}active{% endif %}" 
          href="{% url 'about:author' %}"
          >
          Об авторе
        </a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'about:tech' %}active{% endif %}" href="{% url 'about:tech' %}">Технологии</a>
        </li>
        {% if user.username %}
        <li class="nav-item"> 
          <a class="nav-link {% if view_name  == 'posts:post_create' %}active{% endif %}" href="{% url 'posts:post_create' %}">Новая запись</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light {% if view_name  == 'users:login' %}active{% endif %}" href="{% url 'users:login' %}">Изменить пароль</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light{% if view_name  == 'about:author' %}active{% endif %}" href="{% url 'logout' %}">Выйти</a>
        </li>
        <li>
          Пользователь: {{ user.username }}
        </li>
        {% else %}
        <li class="nav-item"> 
          <a class="nav-link link-light" href="{% url 'users:login' %}">Войти</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light" href="{% url 'users:signup' %}">Регистрация</a>
        </li>
         
        {% endif %}
      </ul>
    </div>
  </nav>{% endwith %}

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% load static %}
<html lang="ru">
<!DOCTYPE html> 
{% block title %} Новый пост {% endblock %}
{% block content %}
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Новый пост
        </div>
        <div class="card-body">
        {% load user_filters %}
          {% if form.errors %}
            {% for field in form %}
              {% for error in field.errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
              <div class="alert alert-danger">
                {{ error|escape }}
              </div>
            {% endfor %}
          {% endif %}
          <form method="post"
            action=
            {% if is_edit %}
            "{% url 'posts:post_edit' post.id %}">
            {% else %}
              "{% url 'posts:post_create' %}">
            {% endif %}
            {% csrf_token %}
            {% for field in form %}
              <div class="form-group row my-3">
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
                </label>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small
                    id="{{ field.id_for_label }}-help"
                    class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            {% endfor %}
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %}
                    Сохранить
                  {% else %}
                    Добавить
                  {% endif %}
                </button>
              </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="ru">
{% block title %}
{{ title }} {{group}}
{% endblock %}
{% block content %}
<div class="container py-5">
  <h1>{{ group.title }}</h1>
  <p>{{ group.description }}</p>
{% for post in page_obj %}
  <ul>
    <li>
      Автор: {{ post.author.get_full_name }}
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
  <p>{{ post.text }}</p>    
  {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
    {% endblock %}

yatube/templates/posts/includes/paginator.html
{# templates/posts/includes/paginator.html #}

{% comment %}
Отрисовываем навигацию паджинатора только если
все посты не помещаются на первую страницу
{% endcomment %}
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}    
  </ul>
</nav>
{% endif %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="ru">
{% block content %}
{% for post in page_obj %}
  <ul>
    <li>
      Автор: {{ post.author.get_full_name }}
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
  <p>{{ post.text }}</p>
  {% if post.group %}
  <a href="{% url 'posts:group_posts' post.group.slug %}">все записи группы</a>
  {% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
    {% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load static %}
<html lang="ru">
{% block title %} {{ post_info.text|truncatechars:30 }} {% endblock %}
{% block content %}
    <div class="row">
      <aside class="col-12 col-md-3">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
                Дата публикации: {{ post_info.pub_date|date:"d E Y" }}
                <li class="list-group-item">Группа: {{ post_info.group }}</p>
              <p>{% if post_info.group %}
                <a href="{% url 'posts:group_posts' post_info.group.slug %}">все записи группы</a>
              {% endif %}</a>
            </li>
            <li class="list-group-item">
              Автор: {{ post_info.author.get_full_name }}</li>
              <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span >{{ authors_post }}</li>
                <li class="list-group-item">
                <a href="{% url 'posts:profile' post_info.author %}">все посты пользователя</a>
              </li>
            </ul>
          </aside
                  <article class="col-12 col-md-9">
                    <p>{{ post_info.text }}</p>
                      {% if post_info.author == request.user %}
                        <a href="{% url 'posts:post_edit' post_info.id %}"> Редактировать запись </a>
                      {% endif %}
                      </article>
                </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %} Профайл пользователя {{ author }} {% endblock %}
{% block content %}
<h1>Все посты пользователя {{ user }}</h1>
        <h3>Всего постов: {{ posts_count }}</h3>   
    {% for post in page_obj %}
        <article>
          <ul>
            <li>
              Автор: {{ post.author.get_full_name }}
              <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>
          <p>{{ post.text }}</p>
          <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
        </article>
        <p>{% if post.group %}
            <a href="{% url 'posts:group_posts' post.group.slug %}">все записи группы</a>
          {% endif %}</p>
{% endfor %}
  {% endblock %}
    

yatube/templates/posts/update_post.html
<{% extends 'base.html' %}
{% load static %}
<html lang="ru">
<!DOCTYPE html> 
{% block title %} Новый пост {% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
            {% if is_edit %} Редактировать пост
            {% else %} Новый пост
            {% endif %}
            </div>
            <div class="card-body">
              {% if is_edit %}
              <form method="POST" class="../posts/update_post.html"> {% else %}
            <form method="POST" class="../posts/create_post.html">
              {% endif %}{% csrf_token %}
              {% for field in form %}
              <div class="form-group row my-3 p-3">
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                    <small id="id_text-help" class="form-text text-muted">
                      Текст нового поста
                    </small>
                  {% endif %}
                </label>    
                {{ field }}
                {% if field.help_text %}
                {% endif %}
              </div>
              {% endfor %}<small id="id_group-help" class="form-text text-muted">
                  Группа, к которой будет относиться пост
                </small>
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %}
                    Сохранить
                  {% else %}
                    Добавить
                  {% endif %}
                </button> 
 {% endblock %}

yatube/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Выход
      </div>
      <div class="card-body">
        <p>
          Вы вышли из своей учётной записи. Ждём вас снова!
        </p>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
{% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}
          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}>
          {% csrf_token %}
          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %} 
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}>
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Войти
            </button>
            {% comment %} 
              <a href="{% url 'users:password_reset_form' %}" class="btn btn-link">
              Забыли пароль?
            </a> 
{% endcomment %}
          </div>
          </form>
        </div>
      </div>
    </div>
</div>
{% endblock %} 

yatube/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Зарегистрироваться
        </div>
        <div class="card-body">
          {% load user_filters %}
          {% if form.errors %}
            {% for field in form %}
              {% for error in field.errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
              <div class="alert alert-danger">
                {{ error|escape }}
              </div>
            {% endfor %}
          {% endif %}
            <form method="post" action="{% url 'users:signup' %}">
              {% csrf_token %}
              {% for field in form %}
              <div class="form-group row my-3 p-3">
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
                </label>
                {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
              {% endfor %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Зарегистрироваться
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
  </div>
{% endblock %} 